// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

import Ahorcado.Partida;

/************************************************************/
/**
 * 
 */
public class Horca {
	/**
	 * 
	 */
	private int fallos;
	/**
	 * 
	 */
	public Partida partida;
	/**
	 * 
	 */
	private boolean brazoIzquierdo;
	/**
	 * 
	 */
	private boolean brazoDerecho;
	/**
	 * 
	 */
	private boolean piernaIzquierda;
	/**
	 * 
	 */
	private boolean piernaDerecha;

	/**
	 * 
	 */
	public void dibujar() {
	}

	/**
	 * 
	 * @param  Incrementa el contador de fallos.
	 */
	public void incrementarFallo() {
	}

	/**
	 * 
	 * @param  Comprueba si hemos perdido una partida.
	 */
	public void comprobarSiPerdido() {
	}
};
