// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

/************************************************************/
/**
 * 
 */
public class Partida {
	/**
	 * 
	 */
	private String nombreJugador;
	/**
	 * 
	 */
	private int puntaje;
	/**
	 * 
	 */
	private int limiteFrases;
	/**
	 * 
	 */
	private int tiempoPorFrase;

	/**
	 * 
	 */
	public void mostrarProgreso() {
	}

	/**
	 * 
	 */
	public void pedirLetra() {
	}

	/**
	 * 
	 */
	public void resolver() {
	}

	/**
	 * 
	 * @return fin 
	 */
	public boolean comprobarFinal() {
	}
};
